- name: Add docker key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/debian/gpg
- name: Add docker repo
  ansible.builtin.apt_repository:
    repo: deb https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable
    state: present
    filename: docker
- name: Install docker-ce
  ansible.builtin.apt:
    name: docker-ce 
    update_cache: yes
- name: Install docker-ce-cli
  ansible.builtin.apt:
    name: docker-ce-cli
- name: Install containerd.io
  ansible.builtin.apt:
    name: containerd.io
- name: Install docker-compose-plugin
  ansible.builtin.apt:
    name: docker-compose-plugin
- name: Install python3-pip
  ansible.builtin.apt:
    name: python3-pip
    update_cache: yes
- name: Install python-requests
  ansible.builtin.pip:
    name: requests
- name: Install python-docker
  ansible.builtin.pip:
    name: docker