---
- name: Full Debian install
  hosts: all
  vars_files:
  - ../../ansible_vars.yml
  tasks:
    - name: Run packages task files
      ansible.builtin.include_tasks: "{{item}}"
      with_fileglob:
        - "packages/*"
    - name: Run docker main task file
      ansible.builtin.include_tasks: docker/main.yml
    - name: Run docker pull task files
      ansible.builtin.include_tasks: "{{item}}"
      with_fileglob:
        - "docker/images/*"
    - name: Hardening System
      ansible.builtin.include_tasks: "{{item}}"
      with_fileglob:
        - "optional_hardening/*"
      ignore_errors: yes
      when: run_hardening == true
    - name: Add Flair
      ansible.builtin.include_tasks: "{{item}}"
      with_fileglob:
        - "flair/*"
      ignore_errors: yes
      when: enable_flair == true
    - name: Run user setup task file
      ansible.builtin.include_tasks: ../user-setup.yml
    - name: Restarting SSH
      ansible.builtin.service:
        name: sshd
        state: restarted